'use strict';

// ============================================================
// hu-web.js — Generated by build.js. Do not edit directly.
// A vim-style, indentation-aware <h-edit> web component.
// Source: lib/constants.js + lang/*.js + lib/buffer.js + lib/keymap.js + lib/engine.js + web/hu-web-src.js
// ============================================================

// --- Constants (from lib/constants.js) ---


// Editor gutter: 4 digits + 1 fold indicator + 1 space
const GUTTER_TOTAL = 6;
// Cursor column offset: gutter + 1-based indexing
const CURSOR_COL_OFFSET = 7;
// Horizontal scroll padding
const H_SCROLL_PAD = 8;

// Indentation
const INDENT = '  ';
const INDENT_SIZE = 2;

// Cheat bar scroll step (pixels per arrow key press)
const CHEAT_SCROLL_STEP = 80;

// Yank panel
const YANK_PANEL_MAX_WIDTH = 50;
const YANK_PANEL_RESERVED_ROWS = 3;

// Undo stack cap
const MAX_UNDO = 100;

  GUTTER_TOTAL, CURSOR_COL_OFFSET, H_SCROLL_PAD,
  INDENT, INDENT_SIZE,
  CHEAT_SCROLL_STEP,
  YANK_PANEL_MAX_WIDTH, YANK_PANEL_RESERVED_ROWS,
  MAX_UNDO,
};



// --- Language configs (generated from lang/) ---

const LANG_CONFIGS = [
  {
    type: 'editable',
    name: 'Hoon',
    extensions: ['.hoon'],
    lineComment: '::',
    selectionUnits: ['line', 'section', 'indent', 'parent'],
    onOpen(buffer) { buffer.autoFold('::'); },
  },
  {
    type: 'editable',
    name: 'HTML',
    extensions: ['.html', '.htm'],
    lineComment: null,
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'JSON',
    extensions: ['.json'],
    lineComment: null,
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'Markdown',
    extensions: ['.md', '.markdown'],
    lineComment: null,
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'Python',
    extensions: ['.py'],
    lineComment: '#',
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'Shell',
    extensions: ['.sh', '.bash', '.zsh'],
    lineComment: '#',
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'Web',
    extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],
    lineComment: '//',
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
  {
    type: 'editable',
    name: 'YAML',
    extensions: ['.yml', '.yaml'],
    lineComment: '#',
    selectionUnits: ['line', 'section', 'indent', 'parent'],
  },
];

const LANG_DEFAULT = {
  type: 'editable',
  name: 'default',
  lineComment: null,
  selectionUnits: ['line', 'section', 'indent', 'parent'],
  onOpen: null,
};

function getLang(filename) {
  if (!filename) return LANG_DEFAULT;
  for (const cfg of LANG_CONFIGS) {
    for (const ext of cfg.extensions) {
      if (filename.endsWith(ext)) return cfg;
    }
  }
  return LANG_DEFAULT;
}


// --- createBuffer (from lib/buffer.js) ---

// Visible index vs actual line number:
// buffer.lines[] is indexed by actual line number. When folds are active,
// visibleLines() returns a filtered array [{lineNum, text}] where lineNum
// is the actual line number. The editor cursor (state.cursor.line) is a
// visible index into this filtered array. Use actualLineNum() to convert
// visible index → actual line number, and findVisibleIndex() for the reverse.

function parseFileContent(content) {
  const lines = content.split('\n');
  if (lines.length > 1 && lines[lines.length - 1] === '') {
    lines.pop();
  }
  return lines;
}

function createBuffer(filename, opts) {
  opts = opts || {};
  const _fs = opts.fs || null;
  const _onSave = opts.onSave || null;

  const buf = {
    lines: [''],
    folds: new Set(),
    filename: filename || '',
    lineComment: null,
    dirty: false,
    stale: false,
    lastMtime: 0,
    _visibleCache: null,

    invalidateCache() {
      buf._visibleCache = null;
    },

    lineCount() {
      return buf.lines.length;
    },

    indentLevel(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return 0;
      const line = buf.lines[lineNum];
      const m = line.match(/^( *)/);
      return m ? m[1].length : 0;
    },

    isBlank(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return true;
      return buf.lines[lineNum].trim().length === 0;
    },

    foldable(lineNum) {
      if (!buf.lineComment) return false;
      if (lineNum < 0 || lineNum >= buf.lines.length - 1) return false;
      if (buf.isBlank(lineNum)) return false;
      const baseIndent = buf.indentLevel(lineNum);
      for (let i = lineNum + 1; i < buf.lines.length; i++) {
        if (!buf.isBlank(i)) {
          if (buf.indentLevel(i) !== baseIndent + 2) return false;
          const trimmed = buf.lines[i].trim();
          return trimmed.startsWith(buf.lineComment) && trimmed.length > 0;
        }
      }
      return false;
    },

    foldRange(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length - 1) return null;
      if (buf.isBlank(lineNum)) return null;
      const baseIndent = buf.indentLevel(lineNum);
      const start = lineNum + 1;
      let end = start;
      while (end < buf.lines.length) {
        if (!buf.isBlank(end) && buf.indentLevel(end) <= baseIndent) break;
        end++;
      }
      if (end === start) return null;
      return [start, end - 1];
    },

    visibleLines() {
      if (buf._visibleCache) return buf._visibleCache;
      const result = [];
      let i = 0;
      while (i < buf.lines.length) {
        result.push({ lineNum: i, text: buf.lines[i] });
        if (buf.folds.has(i)) {
          const range = buf.foldRange(i);
          if (range) {
            i = range[1] + 1;
            continue;
          }
        }
        i++;
      }
      buf._visibleCache = result;
      return result;
    },

    foldedLineCount(lineNum) {
      const range = buf.foldRange(lineNum);
      if (!range) return 0;
      return range[1] - range[0] + 1;
    },

    toggleFold(lineNum) {
      if (buf.folds.has(lineNum)) {
        buf.folds.delete(lineNum);
      } else if (buf.foldable(lineNum)) {
        buf.folds.add(lineNum);
      }
      buf.invalidateCache();
    },

    indentBlock(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return null;
      if (buf.isBlank(lineNum)) return null;
      const indent = buf.indentLevel(lineNum);
      let start = lineNum;
      while (start > 0) {
        if (buf.isBlank(start - 1)) { start--; continue; }
        if (buf.indentLevel(start - 1) >= indent) { start--; } else { break; }
      }
      let end = lineNum;
      while (end < buf.lines.length - 1) {
        if (buf.isBlank(end + 1)) { end++; continue; }
        if (buf.indentLevel(end + 1) >= indent) { end++; } else { break; }
      }
      return [start, end];
    },

    section(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return null;
      if (!buf.isBlank(lineNum) && buf.foldable(lineNum)) {
        const range = buf.foldRange(lineNum);
        return range ? [lineNum, range[1]] : null;
      }
      for (let i = lineNum - 1; i >= 0; i--) {
        if (buf.isBlank(i)) continue;
        if (buf.indentLevel(i) < buf.indentLevel(lineNum)) {
          if (buf.foldable(i)) {
            const range = buf.foldRange(i);
            if (range && lineNum <= range[1]) return [i, range[1]];
          }
          return null;
        }
      }
      return null;
    },

    parentSection(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return null;
      const sec = buf.section(lineNum);
      const header = sec ? sec[0] : lineNum;
      for (let i = header - 1; i >= 0; i--) {
        if (buf.isBlank(i)) continue;
        if (buf.indentLevel(i) < buf.indentLevel(header)) {
          if (buf.foldable(i)) {
            const range = buf.foldRange(i);
            if (range && header <= range[1]) return [i, range[1]];
          }
          return null;
        }
      }
      return null;
    },

    nextSibling(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return null;
      const indent = buf.indentLevel(lineNum);
      for (let i = lineNum + 1; i < buf.lines.length; i++) {
        if (buf.isBlank(i)) continue;
        if (buf.indentLevel(i) === indent) return i;
      }
      return null;
    },

    prevSibling(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return null;
      const indent = buf.indentLevel(lineNum);
      for (let i = lineNum - 1; i >= 0; i--) {
        if (buf.isBlank(i)) continue;
        if (buf.indentLevel(i) === indent) return i;
      }
      return null;
    },

    foldAllAtIndent(indent) {
      let count = 0;
      for (let i = 0; i < buf.lines.length; i++) {
        if (buf.indentLevel(i) === indent && buf.foldable(i)) {
          buf.folds.add(i);
          count++;
        }
      }
      buf.invalidateCache();
      return count;
    },

    autoFold(lineComment) {
      if (!lineComment) return;
      buf.lineComment = lineComment;
      for (let i = 0; i < buf.lines.length; i++) {
        if (buf.foldable(i)) buf.folds.add(i);
      }
      buf.invalidateCache();
    },

    unfoldAll() {
      buf.folds.clear();
      buf.invalidateCache();
    },

    save() {
      if (!buf.filename) return false;
      if (_onSave) {
        _onSave(buf.filename, buf.lines.join('\n') + '\n');
      } else if (_fs) {
        _fs.writeFileSync(buf.filename, buf.lines.join('\n') + '\n');
        // stat may fail if file was just written to a network mount; non-critical
        try { buf.lastMtime = _fs.statSync(buf.filename).mtimeMs; } catch (e) {}
      }
      buf.dirty = false;
      buf.stale = false;
      return true;
    },

    checkStale() {
      if (!_fs || !buf.filename) return false;
      try {
        const mtime = _fs.statSync(buf.filename).mtimeMs;
        if (mtime > buf.lastMtime) {
          buf.stale = true;
          return true;
        }
      } catch (e) { /* file may have been deleted or be inaccessible; not stale */ }
      return false;
    },

    reload() {
      if (!_fs || !buf.filename) return;
      try {
        const content = _fs.readFileSync(buf.filename, 'utf8');
        buf.lines = parseFileContent(content);
        buf.lastMtime = _fs.statSync(buf.filename).mtimeMs;
        buf.dirty = false;
        buf.stale = false;
        buf.invalidateCache();
      } catch (e) { /* file may be gone; keep current buffer contents */ }
    },

    insertLine(lineNum, text) {
      buf.lines.splice(lineNum, 0, text);
      buf.dirty = true;
      buf.invalidateCache();
    },

    deleteLine(lineNum) {
      if (buf.lines.length <= 1) {
        const removed = buf.lines[0];
        buf.lines[0] = '';
        buf.dirty = true;
      buf.invalidateCache();
        return removed;
      }
      const removed = buf.lines.splice(lineNum, 1)[0];
      buf.dirty = true;
      buf.invalidateCache();
      return removed;
    },

    deleteLines(start, end) {
      const removed = buf.lines.splice(start, end - start + 1);
      if (buf.lines.length === 0) buf.lines.push('');
      buf.dirty = true;
      buf.invalidateCache();
      return removed;
    },

    deleteRange(startLine, startCol, endLine, endCol) {
      if (startLine === endLine) {
        const line = buf.lines[startLine];
        const removed = line.slice(startCol, endCol + 1);
        buf.lines[startLine] = line.slice(0, startCol) + line.slice(endCol + 1);
        buf.dirty = true;
      buf.invalidateCache();
        return removed;
      }
      const prefix = buf.lines[startLine].slice(0, startCol);
      const suffix = buf.lines[endLine].slice(endCol + 1);
      const removedParts = [buf.lines[startLine].slice(startCol)];
      for (let i = startLine + 1; i < endLine; i++) {
        removedParts.push(buf.lines[i]);
      }
      removedParts.push(buf.lines[endLine].slice(0, endCol + 1));
      buf.lines[startLine] = prefix + suffix;
      buf.lines.splice(startLine + 1, endLine - startLine);
      if (buf.lines.length === 0) buf.lines.push('');
      buf.dirty = true;
      buf.invalidateCache();
      return removedParts.join('\n');
    },

    insertChar(lineNum, col, ch) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return;
      const line = buf.lines[lineNum];
      buf.lines[lineNum] = line.slice(0, col) + ch + line.slice(col);
      buf.dirty = true;
      buf.invalidateCache();
    },

    deleteChar(lineNum, col) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return;
      const line = buf.lines[lineNum];
      if (col < 0 || col >= line.length) return;
      buf.lines[lineNum] = line.slice(0, col) + line.slice(col + 1);
      buf.dirty = true;
      buf.invalidateCache();
    },

    splitLine(lineNum, col) {
      if (lineNum < 0 || lineNum >= buf.lines.length) return;
      const line = buf.lines[lineNum];
      buf.lines[lineNum] = line.slice(0, col);
      buf.lines.splice(lineNum + 1, 0, line.slice(col));
      buf.dirty = true;
      buf.invalidateCache();
    },

    joinLines(lineNum) {
      if (lineNum < 0 || lineNum >= buf.lines.length - 1) return;
      buf.lines[lineNum] += buf.lines[lineNum + 1];
      buf.lines.splice(lineNum + 1, 1);
      buf.dirty = true;
      buf.invalidateCache();
    },
  };

  if (opts.content != null) {
    buf.lines = parseFileContent(opts.content);
  } else if (_fs && filename) {
    try {
      const content = _fs.readFileSync(filename, 'utf8');
      buf.lines = parseFileContent(content);
      buf.lastMtime = _fs.statSync(filename).mtimeMs;
    } catch (e) {
      if (e.code !== 'ENOENT') throw e;
    }
  }

  return buf;
}




// --- createKeymap (from lib/keymap.js) ---


// Visible index vs actual line number:
// The cursor (state.cursor.line) is a visible index — an offset into the
// array returned by buffer.visibleLines(). This array excludes folded lines.
// To get the actual line number in buffer.lines[], call actualLineNum(buffer).
// To go the other way, call findVisibleIndex(buffer, lineNum).
// All buffer mutations (insert, delete, etc.) use actual line numbers.
// All cursor/selection operations use visible indices.

function createKeymap(state, opts) {
  const execCommand = opts.execCommand;
  const getLang = opts.getLang;

  // --- Mode stack helpers ---

  function pushMode(mode, data = {}) {
    state._modeStack.push({ mode, data });
  }

  function popMode() {
    if (state._modeStack.length <= 1) return null;
    const frame = state._modeStack.pop();
    if (frame.data.onExit) frame.data.onExit();
    return frame;
  }

  function modeData() {
    return state._modeStack[state._modeStack.length - 1].data;
  }

  function modeDepth() {
    return state._modeStack.length;
  }

  // --- Shared helpers ---

  function visibleLineCount(buffer) {
    return buffer.visibleLines().length;
  }

  function clampCursor(buffer) {
    const count = visibleLineCount(buffer);
    if (state.cursor.line >= count) state.cursor.line = Math.max(0, count - 1);
    if (state.cursor.line < 0) state.cursor.line = 0;
    const visible = buffer.visibleLines();
    if (visible[state.cursor.line]) {
      const lineLen = visible[state.cursor.line].text.length;
      if (state.cursor.col > lineLen) state.cursor.col = lineLen;
    }
    if (state.cursor.col < 0) state.cursor.col = 0;
  }

  function createSnapshot(buffer) {
    return { lines: [...buffer.lines], cursor: { ...state.cursor }, folds: new Set(buffer.folds) };
  }

  function restoreSnapshot(buffer, snap) {
    buffer.lines = snap.lines;
    state.cursor = snap.cursor;
    buffer.folds = snap.folds;
    buffer.dirty = true;
    buffer.invalidateCache();
  }

  function pushUndo(buffer) {
    state.undoStack.push(createSnapshot(buffer));
    if (state.undoStack.length > MAX_UNDO) state.undoStack.shift();
    state.redoStack = [];
  }

  function undo(buffer) {
    if (state.undoStack.length === 0) {
      state.message = 'Nothing to undo';
      return;
    }
    state.redoStack.push(createSnapshot(buffer));
    restoreSnapshot(buffer, state.undoStack.pop());
  }

  function redo(buffer) {
    if (state.redoStack.length === 0) {
      state.message = 'Nothing to redo';
      return;
    }
    state.undoStack.push(createSnapshot(buffer));
    restoreSnapshot(buffer, state.redoStack.pop());
  }

  function actualLineNum(buffer) {
    const visible = buffer.visibleLines();
    if (state.cursor.line >= 0 && state.cursor.line < visible.length) {
      return visible[state.cursor.line].lineNum;
    }
    return 0;
  }

  function findVisibleIndex(buffer, lineNum) {
    const visible = buffer.visibleLines();
    for (let i = 0; i < visible.length; i++) {
      if (visible[i].lineNum === lineNum) return i;
      if (visible[i].lineNum > lineNum) return Math.max(0, i - 1);
    }
    return visible.length - 1;
  }

  // Remove a fold on lineNum if it exists
  function unfoldLine(buffer, lineNum) {
    if (buffer.folds.has(lineNum)) {
      buffer.folds.delete(lineNum);
      buffer.invalidateCache();
    }
  }

  // If lineNum is hidden inside a fold, unfold that fold
  function ensureVisible(buffer, lineNum) {
    buffer.invalidateCache();
    for (const foldLn of buffer.folds) {
      const range = buffer.foldRange(foldLn);
      if (range && lineNum >= range[0] && lineNum <= range[1]) {
        buffer.folds.delete(foldLn);
        buffer.invalidateCache();
        return;
      }
    }
  }

  // Smart case: case-insensitive unless query contains uppercase
  function searchIndexOf(text, q, from) {
    if (q !== q.toLowerCase()) return text.indexOf(q, from);
    return text.toLowerCase().indexOf(q, from);
  }

  function searchNext(buffer, dir, inclusive) {
    if (!state.searchQuery) return;
    const visible = buffer.visibleLines();
    const q = state.searchQuery;
    const offset = inclusive ? 0 : 1;

    // Current actual line number
    const curActual = visible[state.cursor.line].lineNum;

    // Check current line for another match beyond (or before) the cursor
    const curText = buffer.lines[curActual];
    if (dir > 0) {
      const next = searchIndexOf(curText, q, state.cursor.col + offset);
      if (next >= 0) {
        state.cursor.col = next;
        state.message = '';
        return;
      }
    } else {
      const limit = inclusive ? state.cursor.col + 1 : state.cursor.col;
      let prev = -1;
      let idx = 0;
      while (idx < limit) {
        const pos = searchIndexOf(curText, q, idx);
        if (pos < 0 || pos >= limit) break;
        prev = pos;
        idx = pos + 1;
      }
      if (prev >= 0 && prev !== state.cursor.col) {
        state.cursor.col = prev;
        state.message = '';
        return;
      }
    }

    // Search all lines (including folded), wrapping around
    const totalLines = buffer.lines.length;
    const start = curActual + dir;
    for (let i = 0; i < totalLines; i++) {
      const lineNum = ((start + i * dir) % totalLines + totalLines) % totalLines;
      const text = buffer.lines[lineNum];
      if (searchIndexOf(text, q, 0) >= 0) {
        // Unfold if this line is hidden
        ensureVisible(buffer, lineNum);
        // Recompute visible lines after potential unfold
        const newVisible = buffer.visibleLines();
        state.cursor.line = findVisibleIndex(buffer, lineNum);
        if (dir > 0) {
          state.cursor.col = searchIndexOf(text, q, 0);
        } else {
          let last = -1;
          let si = 0;
          while (si < text.length) {
            const pos = searchIndexOf(text, q, si);
            if (pos < 0) break;
            last = pos;
            si = pos + 1;
          }
          state.cursor.col = last;
        }
        state.message = '';
        return;
      }
    }
    state.message = 'Pattern not found';
  }

  function getCharRange(visible) {
    if (!state.selection) return null;
    const anchorLn = visible[state.selection.anchor].lineNum;
    const headLn = visible[state.selection.head].lineNum;
    const anchorCol = state.selection.anchorCol;
    const headCol = state.cursor.col;
    if (anchorLn < headLn || (anchorLn === headLn && anchorCol <= headCol)) {
      return { startLine: anchorLn, startCol: anchorCol, endLine: headLn, endCol: headCol };
    }
    return { startLine: headLn, startCol: headCol, endLine: anchorLn, endCol: anchorCol };
  }

  // direction: 'after' (p) or 'before' (P)
  function pasteContent(buffer, ctx, direction) {
    if (state.yankBuf.length === 0) {
      state.message = 'Nothing to paste';
      return;
    }
    pushUndo(buffer);
    unfoldLine(buffer, ctx.ln);
    if (state.yankType === 'char') {
      const text = state.yankBuf[0];
      const parts = text.split('\n');
      const col = direction === 'after' ? state.cursor.col + 1 : state.cursor.col;
      if (parts.length === 1) {
        buffer.insertChar(ctx.ln, col, text);
        state.cursor.col = col + text.length - 1;
      } else {
        const line = buffer.lines[ctx.ln];
        const before = line.slice(0, col);
        const after = line.slice(col);
        buffer.lines[ctx.ln] = before + parts[0];
        for (let i = 1; i < parts.length - 1; i++) {
          buffer.insertLine(ctx.ln + i, parts[i]);
        }
        buffer.insertLine(ctx.ln + parts.length - 1, parts[parts.length - 1] + after);
        state.cursor.line += parts.length - 1;
        state.cursor.col = parts[parts.length - 1].length;
        buffer.dirty = true;
        buffer.invalidateCache();
      }
      state.message = 'Pasted inline';
    } else {
      const offset = direction === 'after' ? 1 : 0;
      for (let i = 0; i < state.yankBuf.length; i++) {
        buffer.insertLine(ctx.ln + offset + i, state.yankBuf[i]);
      }
      if (direction === 'after') state.cursor.line++;
      state.message = `${state.yankBuf.length} line(s) pasted`;
    }
  }

  // --- Keymaps ---

  const normalKeymap = [
    {
      cheat: ['j/k', 'move'], desc: 'Move cursor up/down',
      keys: ['j', 'down', 'k', 'up'],
      fn(key, buffer, ctx) {
        if (key.key === 'j' || key.key === 'down') {
          state.cursor.line = Math.min(state.cursor.line + 1, ctx.visible.length - 1);
        } else {
          state.cursor.line = Math.max(state.cursor.line - 1, 0);
        }
      }
    },
    {
      cheat: ['h/l', 'col'], desc: 'Move cursor left/right',
      keys: ['h', 'l'],
      fn(key, buffer, ctx) {
        if (key.key === 'h') {
          state.cursor.col = Math.max(state.cursor.col - 1, 0);
        } else if (ctx.visible[state.cursor.line]) {
          state.cursor.col = Math.min(state.cursor.col + 1, ctx.visible[state.cursor.line].text.length);
        }
      }
    },
    {
      cheat: ['w/b', 'word'], desc: 'Next/prev non-whitespace group',
      keys: ['w', 'b'],
      fn(key, buffer, ctx) {
        const line = ctx.visible[state.cursor.line] ? ctx.visible[state.cursor.line].text : '';
        let pos = state.cursor.col;
        if (key.key === 'w') {
          while (pos < line.length && line[pos] !== ' ') pos++;
          while (pos < line.length && line[pos] === ' ') pos++;
        } else {
          if (pos > 0) pos--;
          while (pos > 0 && line[pos] === ' ') pos--;
          while (pos > 0 && line[pos - 1] !== ' ') pos--;
        }
        state.cursor.col = pos;
      }
    },
    {
      cheat: null, desc: null,
      keys: ['left', 'right'],
      fn(key) {
        if (key.key === 'left') {
          state.cheatScrollPx = Math.max(0, (state.cheatScrollPx || 0) - CHEAT_SCROLL_STEP);
        } else {
          state.cheatScrollPx = (state.cheatScrollPx || 0) + CHEAT_SCROLL_STEP;
        }
      }
    },
    {
      cheat: ['J/K', 'barrier'], desc: 'Barrier jump up/down',
      keys: ['J', 'K'],
      fn(key, buffer, ctx) {
        const col = state.cursor.col;
        const dir = key.key === 'J' ? 1 : -1;
        let row = state.cursor.line;
        function isWsAtRow(r) {
          const text = ctx.visible[r]?.text || '';
          if (text.trim().length === 0) return 'blank';
          if (col >= text.length) return 'short';
          return text[col] === ' ' || text[col] === '\t';
        }
        const startStatus = isWsAtRow(row);
        let skippedShort = false;
        let next = row + dir;
        while (next >= 0 && next < ctx.visible.length) {
          const nextStatus = isWsAtRow(next);
          if (nextStatus === 'short') { skippedShort = true; next += dir; continue; }
          if (startStatus === 'blank') {
            if (nextStatus !== 'blank') { row = next; break; }
          } else {
            if (nextStatus === 'blank' || nextStatus !== startStatus) { row = next; break; }
          }
          next += dir;
        }
        if (skippedShort && next >= 0 && next < ctx.visible.length) {
          next = row + dir;
          while (next >= 0 && next < ctx.visible.length) {
            if (isWsAtRow(next) !== 'short') { row = next; break; }
            next += dir;
          }
        }
        if (next >= 0 && next < ctx.visible.length) {
          state.cursor.line = row;
        }
      }
    },
    {
      cheat: ['q/z', 'outdent'], desc: 'Nearest less-indented line above/below',
      keys: ['q', 'z'],
      fn(key, buffer, ctx) {
        const indent = buffer.indentLevel(ctx.ln);
        if (key.key === 'q') {
          for (let i = ctx.ln - 1; i >= 0; i--) {
            if (buffer.isBlank(i)) continue;
            if (buffer.indentLevel(i) < indent) {
              state.cursor.line = findVisibleIndex(buffer, i);
              state.cursor.col = buffer.indentLevel(i);
              break;
            }
          }
        } else {
          for (let i = ctx.ln + 1; i < buffer.lines.length; i++) {
            if (buffer.isBlank(i)) continue;
            if (buffer.indentLevel(i) < indent) {
              state.cursor.line = findVisibleIndex(buffer, i);
              state.cursor.col = buffer.indentLevel(i);
              break;
            }
          }
        }
      }
    },
    {
      cheat: ['g/G', 'top/bot'], desc: 'Top / bottom of file',
      keys: ['g', 'G'],
      fn(key, buffer, ctx) {
        if (key.key === 'g') {
          state.cursor.line = 0;
          state.cursor.col = 0;
        } else {
          state.cursor.line = ctx.visible.length - 1;
          state.cursor.col = 0;
        }
      }
    },
    {
      cheat: ['H/L', 'barrier'], desc: 'Barrier jump left/right',
      keys: ['H', 'L'],
      fn(key, buffer, ctx) {
        const line = ctx.visible[state.cursor.line]?.text || '';
        const col = state.cursor.col;
        const curIsWs = col >= line.length || line[col] === ' ' || line[col] === '\t';
        if (key.key === 'H') {
          for (let c = col - 1; c >= 0; c--) {
            const charIsWs = line[c] === ' ' || line[c] === '\t';
            if (charIsWs !== curIsWs) { state.cursor.col = c; return; }
          }
        } else {
          for (let c = col + 1; c <= line.length; c++) {
            const charIsWs = c >= line.length || line[c] === ' ' || line[c] === '\t';
            if (charIsWs !== curIsWs) { state.cursor.col = c; return; }
          }
        }
      }
    },
    {
      cheat: ['</>',  'indent'], desc: 'Outdent / indent line',
      keys: ['<', '>'],
      fn(key, buffer, ctx) {
        pushUndo(buffer);
        if (key.key === '<') {
          if (buffer.lines[ctx.ln].startsWith(INDENT)) {
            buffer.lines[ctx.ln] = buffer.lines[ctx.ln].slice(INDENT_SIZE);
            state.cursor.col = Math.max(0, state.cursor.col - INDENT_SIZE);
          } else if (buffer.lines[ctx.ln].startsWith(' ')) {
            buffer.lines[ctx.ln] = buffer.lines[ctx.ln].slice(1);
            state.cursor.col = Math.max(0, state.cursor.col - 1);
          }
        } else {
          buffer.lines[ctx.ln] = INDENT + buffer.lines[ctx.ln];
          state.cursor.col += INDENT_SIZE;
        }
        buffer.dirty = true;
        buffer.invalidateCache();
        ensureVisible(buffer, ctx.ln);
        state.cursor.line = findVisibleIndex(buffer, ctx.ln);
      }
    },
    {
      cheat: ['Tab', 'fold'], desc: 'Toggle fold',
      keys: ['tab'],
      fn(key, buffer, ctx) {
        if (ctx.visible[state.cursor.line]) {
          const tabLn = ctx.visible[state.cursor.line].lineNum;
          if (buffer.foldable(tabLn)) {
            buffer.toggleFold(tabLn);
          } else {
            const sec = buffer.section(tabLn);
            if (sec) {
              buffer.toggleFold(sec[0]);
              state.cursor.line = findVisibleIndex(buffer, sec[0]);
            }
          }
          clampCursor(buffer);
        }
      }
    },
    {
      cheat: ['F', 'fold all'], desc: 'Fold all at cursor indent',
      keys: ['F'],
      fn(key, buffer, ctx) {
        const indent = buffer.indentLevel(ctx.ln);
        const count = buffer.foldAllAtIndent(indent);
        clampCursor(buffer);
        state.message = `Folded ${count} blocks at indent ${indent}`;
      }
    },
    {
      cheat: ['E', 'expand'], desc: 'Expand all',
      keys: ['E'],
      fn(key, buffer) {
        buffer.unfoldAll();
        state.message = 'Expanded all';
      }
    },
    {
      cheat: ['Space', 'select'], desc: 'Start line selection',
      keys: [' '],
      fn() {
        pushMode('select', { onExit() { state.selection = null; } });
        state.selectionUnit = 'line';
        state.selection = { anchor: state.cursor.line, head: state.cursor.line };
      }
    },
    {
      cheat: ['v', 'v-sel'], desc: 'Start char selection',
      keys: ['v'],
      fn() {
        pushMode('select', { onExit() { state.selection = null; } });
        state.selectionUnit = 'char';
        state.selection = { anchor: state.cursor.line, head: state.cursor.line, anchorCol: state.cursor.col };
      }
    },
    {
      cheat: ['i/a/I/A', 'insert'], desc: 'Insert before/after/start/end',
      keys: ['i', 'a', 'I', 'A'],
      fn(key, buffer, ctx) {
        pushUndo(buffer);
        pushMode('insert');
        if (key.key === 'a' && ctx.visible[state.cursor.line]) {
          state.cursor.col = Math.min(state.cursor.col + 1, ctx.visible[state.cursor.line].text.length);
        } else if (key.key === 'I') {
          const text = ctx.visible[state.cursor.line] ? ctx.visible[state.cursor.line].text : '';
          const m = text.match(/\S/);
          state.cursor.col = m ? m.index : 0;
        } else if (key.key === 'A' && ctx.visible[state.cursor.line]) {
          state.cursor.col = ctx.visible[state.cursor.line].text.length;
        }
      }
    },
    {
      cheat: ['o/O', 'open line'], desc: 'New line below/above',
      keys: ['o', 'O'],
      fn(key, buffer, ctx) {
        pushUndo(buffer);
        unfoldLine(buffer, ctx.ln);
        const indent = buffer.indentLevel(ctx.ln);
        if (key.key === 'o') {
          buffer.insertLine(ctx.ln + 1, ' '.repeat(indent));
          state.cursor.line++;
          state.cursor.col = indent;
        } else {
          buffer.insertLine(ctx.ln, ' '.repeat(indent));
          state.cursor.col = indent;
        }
        pushMode('insert');
      }
    },
    {
      cheat: ['c', 'clear eol'], desc: 'Clear to end of line, insert',
      keys: ['c'],
      fn(key, buffer, ctx) {
        if (ctx.ln < 0 || ctx.ln >= buffer.lines.length) return;
        pushUndo(buffer);
        const line = buffer.lines[ctx.ln];
        const killed = line.slice(state.cursor.col);
        buffer.lines[ctx.ln] = line.slice(0, state.cursor.col);
        buffer.dirty = true;
        buffer.invalidateCache();
        if (killed.length > 0) state.yankBuf = [killed];
        state.yankType = 'char';
        pushMode('insert');
      }
    },
    {
      cheat: ['d', 'del'], desc: 'Delete line',
      keys: ['d'],
      fn(key, buffer, ctx) {
        if (ctx.ln < 0 || ctx.ln >= buffer.lines.length) return;
        pushUndo(buffer);
        unfoldLine(buffer, ctx.ln);
        const removed = buffer.deleteLine(ctx.ln);
        state.yankBuf = [removed];
        state.yankType = 'line';
        state.message = '1 line deleted';
        clampCursor(buffer);
      }
    },
    {
      cheat: ['y', 'yank'], desc: 'Yank line',
      keys: ['y'],
      fn(key, buffer, ctx) {
        state.yankBuf = [buffer.lines[ctx.ln]];
        state.yankType = 'line';
        state.message = '1 line yanked';
      }
    },
    {
      cheat: ['p', 'paste'], desc: 'Paste below',
      keys: ['p'],
      fn(key, buffer, ctx) {
        pasteContent(buffer, ctx, 'after');
      }
    },
    {
      cheat: ['P', 'paste above'], desc: 'Paste above',
      keys: ['P'],
      fn(key, buffer, ctx) {
        pasteContent(buffer, ctx, 'before');
      }
    },
    {
      cheat: ['"', 'regs'], desc: 'Yank registers',
      keys: ['"'],
      panel: 'yank',
      onOpen() { state.yankPanelIdx = 0; },
      menu: [
        {
          cheat: ['j/k', 'nav'], desc: 'Navigate registers',
          keys: ['j', 'k', 'up', 'down'],
          fn(key) {
            const regCount = 1 + state.yankMap.size;
            if (key.key === 'j' || key.key === 'down') {
              state.yankPanelIdx = Math.min(state.yankPanelIdx + 1, regCount - 1);
            } else {
              state.yankPanelIdx = Math.max(state.yankPanelIdx - 1, 0);
            }
          },
        },
        {
          cheat: ['p', 'paste'], desc: 'Paste from register',
          keys: ['p'],
          fn(key, buffer) {
            let lines;
            if (state.yankPanelIdx === 0) {
              lines = state.yankBuf;
            } else {
              const keys = [...state.yankMap.keys()];
              lines = state.yankMap.get(keys[state.yankPanelIdx - 1])?.lines || [];
            }
            if (lines.length > 0) {
              pushUndo(buffer);
              const ln = actualLineNum(buffer);
              unfoldLine(buffer, ln);
              for (let i = 0; i < lines.length; i++) {
                buffer.insertLine(ln + 1 + i, lines[i]);
              }
              state.cursor.line++;
              state.message = `${lines.length} line(s) pasted`;
            }
            popMode();
          },
        },
        {
          cheat: ['s', 'save'], desc: 'Save to register',
          keys: ['s'],
          fn() {
            pushMode('prompt', {
              prefix: 'label: ',
              buf: '',
              col: 0,
              label: 'REGISTER LABEL',
              onDone(val) {
                const label = val.trim();
                if (label && state.yankBuf.length > 0) {
                  const used = new Set(state.yankMap.keys());
                  let regKey = null;
                  for (let c = 97; c <= 122; c++) {
                    const ch = String.fromCharCode(c);
                    if (!used.has(ch)) { regKey = ch; break; }
                  }
                  if (regKey) {
                    state.yankMap.set(regKey, { label, lines: [...state.yankBuf] });
                    state.message = `Saved to register ${regKey}`;
                  } else {
                    state.message = 'All registers full';
                  }
                }
              },
            });
          },
        },
        {
          cheat: ['d', 'del'], desc: 'Delete register',
          keys: ['d'],
          fn() {
            if (state.yankPanelIdx > 0) {
              const keys = [...state.yankMap.keys()];
              state.yankMap.delete(keys[state.yankPanelIdx - 1]);
              state.yankPanelIdx = Math.max(0, state.yankPanelIdx - 1);
            }
          },
        },
        {
          cheat: ['"', 'close'], desc: 'Close panel',
          keys: ['"'],
          fn() {
            popMode();
          },
        },
        { cheat: ['Esc', 'close'], desc: 'Close panel', keys: null },
      ],
    },
    {
      cheat: ['u/r', 'undo'], desc: 'Undo / redo',
      keys: ['u', 'r'],
      fn(key, buffer) {
        if (key.key === 'u') undo(buffer);
        else redo(buffer);
      }
    },
    {
      cheat: ['/', 'search'], desc: 'Search',
      keys: ['/'],
      fn() {
        pushMode('prompt', {
          prefix: '/',
          buf: '',
          col: 0,
          label: 'SEARCH',
          _prevQuery: state.searchQuery || '',
          onDone(val, buffer) { state.searchQuery = val; searchNext(buffer, 1, true); },
        });
      }
    },
    {
      cheat: ['n/N', 'next/prev'], desc: 'Next/prev search result',
      keys: ['n', 'N'],
      fn(key, buffer) {
        searchNext(buffer, key.key === 'n' ? 1 : -1);
      }
    },
    {
      cheat: ['s', 'save'], desc: 'Save file',
      keys: ['s'],
      fn(key, buffer) {
        if (buffer.save()) {
          state.message = `Saved ${buffer.filename}`;
        } else {
          state.message = 'No filename';
        }
      }
    },
    {
      cheat: [':', 'cmd'], desc: 'Command mode',
      keys: [':'],
      fn() {
        pushMode('prompt', {
          prefix: ':',
          buf: '',
          col: 0,
          label: 'COMMAND',
          onDone(val, buffer) { execCommand(val, buffer); },
        });
      }
    },
  ];

  const selectKeymap = [
    {
      cheat: ['h/l', 'col'], desc: 'Extend char selection left/right',
      keys: ['h', 'l', 'left', 'right'],
      fn(key, buffer, ctx) {
        if (state.selectionUnit !== 'char') return;
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['w/b', 'word'], desc: 'Extend char selection by word',
      keys: ['w', 'b'],
      fn(key, buffer, ctx) {
        if (state.selectionUnit !== 'char') return;
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['j/k', 'extend'], desc: 'Extend selection',
      keys: ['j', 'down', 'k', 'up'],
      fn(key, buffer, ctx) {
        if (key.key === 'j' || key.key === 'down') {
          state.selection.head = Math.min(state.selection.head + 1, ctx.visible.length - 1);
        } else {
          state.selection.head = Math.max(state.selection.head - 1, 0);
        }
        state.cursor.line = state.selection.head;
      }
    },
    {
      cheat: ['J/K', 'barrier'], desc: 'Barrier jump up/down',
      keys: ['J', 'K'],
      fn(key, buffer) {
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['q/z', 'outdent'], desc: 'Nearest less-indented line above/below',
      keys: ['q', 'z'],
      fn(key, buffer) {
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['g/G', 'top/bot'], desc: 'Top / bottom of file',
      keys: ['g', 'G'],
      fn(key, buffer) {
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['Space', 'cycle unit'], desc: 'Cycle unit (line/section/indent/parent)',
      keys: [' '],
      fn(key, buffer, ctx) {
        if (state.selectionUnit === 'char') {
          state.selectionUnit = 'line';
          state.selection = { anchor: state.cursor.line, head: state.cursor.line };
          return;
        }
        const units = getLang(buffer.filename).selectionUnits;
        const idx = units.indexOf(state.selectionUnit);
        state.selectionUnit = units[(idx + 1) % units.length];
        let range = null;
        switch (state.selectionUnit) {
          case 'section': range = buffer.section(ctx.ln); break;
          case 'indent': range = buffer.indentBlock(ctx.ln); break;
          case 'parent': range = buffer.parentSection(ctx.ln); break;
          default:
            state.selection = { anchor: state.cursor.line, head: state.cursor.line };
            return;
        }
        if (range) {
          state.selection = {
            anchor: findVisibleIndex(buffer, range[0]),
            head: findVisibleIndex(buffer, range[1]),
          };
        }
      }
    },
    {
      cheat: ['d', 'del'], desc: 'Delete selection',
      keys: ['d'],
      fn(key, buffer, ctx) {
        if (!state.selection) return;
        pushUndo(buffer);
        if (state.selectionUnit === 'char') {
          const r = getCharRange(ctx.visible);
          const removed = buffer.deleteRange(r.startLine, r.startCol, r.endLine, r.endCol);
          state.yankBuf = [removed];
          state.yankType = 'char';
          state.cursor.line = findVisibleIndex(buffer, r.startLine);
          state.cursor.col = r.startCol;
          state.message = 'Char range deleted';
        } else {
          const start = Math.min(state.selection.anchor, state.selection.head);
          const end = Math.max(state.selection.anchor, state.selection.head);
          const startLn = ctx.visible[start].lineNum;
          const endLn = ctx.visible[end].lineNum;
          const removed = buffer.deleteLines(startLn, endLn);
          state.yankBuf = removed;
          state.yankType = 'line';
          state.message = `${removed.length} line(s) deleted`;
        }
        popMode();
        clampCursor(buffer);
      }
    },
    {
      cheat: ['y', 'yank'], desc: 'Yank selection',
      keys: ['y'],
      fn(key, buffer, ctx) {
        if (!state.selection) return;
        if (state.selectionUnit === 'char') {
          const r = getCharRange(ctx.visible);
          const parts = [];
          if (r.startLine === r.endLine) {
            parts.push(buffer.lines[r.startLine].slice(r.startCol, r.endCol + 1));
          } else {
            parts.push(buffer.lines[r.startLine].slice(r.startCol));
            for (let i = r.startLine + 1; i < r.endLine; i++) {
              parts.push(buffer.lines[i]);
            }
            parts.push(buffer.lines[r.endLine].slice(0, r.endCol + 1));
          }
          state.yankBuf = [parts.join('\n')];
          state.yankType = 'char';
          state.message = 'Char range yanked';
        } else {
          const start = Math.min(state.selection.anchor, state.selection.head);
          const end = Math.max(state.selection.anchor, state.selection.head);
          const startLn = ctx.visible[start].lineNum;
          const endLn = ctx.visible[end].lineNum;
          state.yankBuf = buffer.lines.slice(startLn, endLn + 1);
          state.yankType = 'line';
          state.message = `${state.yankBuf.length} line(s) yanked`;
        }
        popMode();
      }
    },
    {
      cheat: ['H/L', 'barrier'], desc: 'Barrier jump left/right (extend char selection)',
      keys: ['H', 'L'],
      fn(key, buffer) {
        if (state.selectionUnit !== 'char') return;
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['</>',  'indent'], desc: 'Indent/dedent selection',
      keys: ['>', '<'],
      fn(key, buffer, ctx) {
        if (!state.selection) return;
        pushUndo(buffer);
        const start = Math.min(state.selection.anchor, state.selection.head);
        const end = Math.max(state.selection.anchor, state.selection.head);
        for (let i = start; i <= end; i++) {
          const ln = ctx.visible[i].lineNum;
          if (key.key === '>') {
            buffer.lines[ln] = INDENT + buffer.lines[ln];
          } else {
            if (buffer.lines[ln].startsWith(INDENT)) {
              buffer.lines[ln] = buffer.lines[ln].slice(INDENT_SIZE);
            } else if (buffer.lines[ln].startsWith(' ')) {
              buffer.lines[ln] = buffer.lines[ln].slice(1);
            }
          }
        }
        buffer.dirty = true;
        buffer.invalidateCache();
        const startLn = ctx.visible[start].lineNum;
        const endLn = ctx.visible[end].lineNum;
        for (let i = start; i <= end; i++) {
          ensureVisible(buffer, ctx.visible[i].lineNum);
        }
        state.selection.anchor = findVisibleIndex(buffer, startLn);
        state.selection.head = findVisibleIndex(buffer, endLn);
        state.cursor.line = state.selection.head;
        state.message = key.key === '>' ? 'Indented' : 'Dedented';
      }
    },
    {
      cheat: ['n/N', 'search'], desc: 'Next/prev search result',
      keys: ['n', 'N'],
      fn(key, buffer) {
        dispatch(normalKeymap, key, buffer);
        state.selection.head = state.cursor.line;
      }
    },
    {
      cheat: ['Tab', 'fold'], desc: 'Fold selection',
      keys: ['tab'],
      fn(key, buffer, ctx) {
        if (!state.selection) return;
        const start = Math.min(state.selection.anchor, state.selection.head);
        const startLn = ctx.visible[start].lineNum;
        if (buffer.foldable(startLn)) {
          buffer.folds.add(startLn);
          popMode();
          clampCursor(buffer);
        }
      }
    },
    {
      cheat: ['Esc', 'cancel'], desc: 'Cancel selection',
      keys: ['escape'],
      fn() {
        popMode();
      }
    },
  ];

  const insertKeymap = [
    {
      cheat: ['type', 'insert'], desc: 'Insert characters',
      keys: null,
    },
    {
      cheat: ['Enter', 'newline'], desc: 'New line (auto-indent)',
      keys: ['enter'],
      fn(key, buffer, ctx) {
        unfoldLine(buffer, ctx.ln);
        const indent = buffer.indentLevel(ctx.ln);
        buffer.splitLine(ctx.ln, state.cursor.col);
        state.cursor.line++;
        const newLn = ctx.ln + 1;
        const spaces = ' '.repeat(indent);
        buffer.lines[newLn] = spaces + buffer.lines[newLn].trimStart();
        state.cursor.col = indent;
      }
    },
    {
      cheat: ['Bksp', 'del back'], desc: 'Delete behind',
      keys: ['backspace'],
      fn(key, buffer, ctx) {
        if (state.cursor.col > 0) {
          buffer.deleteChar(ctx.ln, state.cursor.col - 1);
          state.cursor.col--;
        } else if (ctx.ln > 0) {
          unfoldLine(buffer, ctx.ln - 1);
          const prevLen = buffer.lines[ctx.ln - 1].length;
          buffer.joinLines(ctx.ln - 1);
          state.cursor.line--;
          state.cursor.col = prevLen;
        }
      }
    },
    {
      cheat: ['Del', 'del fwd'], desc: 'Delete ahead',
      keys: ['delete'],
      fn(key, buffer, ctx) {
        if (state.cursor.col < buffer.lines[ctx.ln].length) {
          buffer.deleteChar(ctx.ln, state.cursor.col);
        } else if (ctx.ln < buffer.lines.length - 1) {
          unfoldLine(buffer, ctx.ln);
          buffer.joinLines(ctx.ln);
        }
      }
    },
    {
      cheat: ['\u2191\u2193\u2190\u2192', 'move'], desc: 'Move cursor',
      keys: ['left', 'right', 'up', 'down'],
      fn(key, buffer, ctx) {
        switch (key.key) {
          case 'left':
            state.cursor.col = Math.max(0, state.cursor.col - 1);
            break;
          case 'right':
            state.cursor.col = Math.min(buffer.lines[ctx.ln].length, state.cursor.col + 1);
            break;
          case 'up':
            state.cursor.line = Math.max(0, state.cursor.line - 1);
            break;
          case 'down':
            state.cursor.line = Math.min(ctx.visible.length - 1, state.cursor.line + 1);
            break;
        }
      }
    },
    {
      cheat: ['Tab', 'indent'], desc: 'Insert two spaces',
      keys: ['tab'], shift: false,
      fn(key, buffer, ctx) {
        buffer.insertChar(ctx.ln, state.cursor.col, INDENT);
        state.cursor.col += INDENT_SIZE;
      }
    },
    {
      cheat: ['S-Tab', 'dedent'], desc: 'Remove two spaces of indent',
      keys: ['tab'], shift: true,
      fn(key, buffer, ctx) {
        const line = buffer.lines[ctx.ln];
        const spaces = line.length - line.trimStart().length;
        const remove = Math.min(INDENT_SIZE, spaces);
        if (remove > 0) {
          for (let i = 0; i < remove; i++) buffer.deleteChar(ctx.ln, 0);
          state.cursor.col = Math.max(0, state.cursor.col - remove);
        }
      }
    },
    {
      cheat: ['Home/End', 'home/end'], desc: 'Beginning/end of line',
      keys: ['home', 'end'],
      fn(key, buffer, ctx) {
        if (key.key === 'home') {
          state.cursor.col = 0;
        } else {
          state.cursor.col = buffer.lines[ctx.ln].length;
        }
      }
    },
    {
      cheat: ['Esc', 'normal'], desc: 'Return to normal mode',
      keys: ['escape'],
      fn() {
        popMode();
      }
    },
  ];

  // --- Prompt helpers ---

  function getPromptBuf() {
    if (state.mode === 'prompt') return modeData().buf;
    return state.mode === 'command' ? state.commandBuf : state.searchBuf;
  }

  function setPromptBuf(val) {
    if (state.mode === 'prompt') { modeData().buf = val; return; }
    if (state.mode === 'command') state.commandBuf = val;
    else state.searchBuf = val;
  }

  function exitPrompt() {
    popMode();
  }

  const promptKeymap = [
    {
      cheat: ['\u2190\u2192', 'move'], desc: 'Move cursor in prompt',
      keys: ['left', 'right'],
      fn(key) {
        const buf = getPromptBuf();
        if (key.key === 'left') {
          state.promptCol = Math.max(0, state.promptCol - 1);
        } else {
          state.promptCol = Math.min(buf.length, state.promptCol + 1);
        }
      }
    },
    {
      cheat: ['Home/End', 'home/end'], desc: 'Beginning/end of prompt',
      keys: ['home', 'end'],
      fn(key) {
        if (key.key === 'home') {
          state.promptCol = 0;
        } else {
          state.promptCol = getPromptBuf().length;
        }
      }
    },
    {
      cheat: ['Bksp', 'del back'], desc: 'Delete behind',
      keys: ['backspace'],
      fn() {
        const buf = getPromptBuf();
        if (state.promptCol > 0) {
          setPromptBuf(buf.slice(0, state.promptCol - 1) + buf.slice(state.promptCol));
          state.promptCol--;
        } else if (buf.length === 0) {
          exitPrompt();
        }
      }
    },
    {
      cheat: ['Del', 'del fwd'], desc: 'Delete forward',
      keys: ['delete'],
      fn() {
        const buf = getPromptBuf();
        if (state.promptCol < buf.length) {
          setPromptBuf(buf.slice(0, state.promptCol) + buf.slice(state.promptCol + 1));
        }
      }
    },
    {
      cheat: ['Enter', 'submit'], desc: 'Submit', keys: null,
    },
    {
      cheat: ['Esc', 'cancel'], desc: 'Cancel', keys: null,
    },
  ];

  // --- Dispatch + mode handlers ---

  function dispatch(keymap, key, buffer) {
    const visible = buffer.visibleLines();
    const ln = actualLineNum(buffer);
    const ctx = { visible, ln };
    for (const entry of keymap) {
      if (!entry.keys) continue;
      if ((entry.ctrl || false) !== !!key.ctrl) continue;
      if (entry.shift !== undefined && (entry.shift || false) !== !!key.shift) continue;
      if (entry.keys.includes(key.key)) {
        if (entry.menu) {
          pushMode('menu', {
            keymap: entry.menu,
            label: entry.desc || 'MENU',
            panel: entry.panel || null,
          });
          if (entry.onOpen) entry.onOpen();
          return true;
        }
        entry.fn(key, buffer, ctx);
        return true;
      }
    }
    return false;
  }

  function handleInsert(key, buffer) {
    if (dispatch(insertKeymap, key, buffer)) return;
    if (!key.ctrl && key.key.length === 1 && key.key.charCodeAt(0) >= 32) {
      const ln = actualLineNum(buffer);
      buffer.insertChar(ln, state.cursor.col, key.key);
      state.cursor.col++;
    }
  }

  function handlePrompt(key, buffer) {
    const d = modeData();
    if (key.key === 'escape') {
      // Restore previous search query on cancel
      if (d.prefix === '/' && d._prevQuery !== undefined) {
        state.searchQuery = d._prevQuery;
      }
      popMode();
      return;
    }
    if (key.key === 'enter') {
      const val = d.buf;
      const onDone = d.onDone;
      popMode();
      if (onDone) onDone(val, buffer);
      return;
    }
    if (dispatch(promptKeymap, key, buffer)) {
      if (d.prefix === '/') state.searchQuery = d.buf;
      return;
    }
    if (key.key.length === 1 && !key.ctrl) {
      d.buf = d.buf.slice(0, d.col) + key.key + d.buf.slice(d.col);
      d.col++;
    }
    // Live search highlight as user types
    if (d.prefix === '/') state.searchQuery = d.buf;
  }

  function handleMenu(key, buffer) {
    if (key.key === 'escape') {
      popMode();
      return;
    }
    const d = modeData();
    dispatch(d.keymap, key, buffer);
  }

  function handleKey(key, buffer) {
    state.message = '';

    switch (state.mode) {
      case 'normal': dispatch(normalKeymap, key, buffer); break;
      case 'select': dispatch(selectKeymap, key, buffer); break;
      case 'insert': handleInsert(key, buffer); break;
      case 'prompt': handlePrompt(key, buffer); break;
      case 'menu': handleMenu(key, buffer); break;
    }

    clampCursor(buffer);
  }

  return {
    normalKeymap, selectKeymap, insertKeymap, promptKeymap,
    dispatch, handleKey, handleInsert,
    clampCursor, actualLineNum, findVisibleIndex,
    pushUndo, undo, redo,
    pushMode, popMode, modeData, modeDepth,
  };
}




// --- Engine (from lib/engine.js) ---



// --- createState: shared editor state ---

function createState(extraFields) {
  const state = {
    _modeStack: [{ mode: 'normal', data: {} }],
    cursor: { line: 0, col: 0 },
    selection: null,
    selectionUnit: 'line',
    scroll: 0,
    scrollX: 0,
    _commandBuf: '',
    _searchBuf: '',
    searchQuery: '',
    _promptCol: 0,
    message: '',
    yankBuf: [],
    yankType: 'line',
    yankMap: new Map(),
    yankPanelIdx: 0,
    undoStack: [],
    redoStack: [],
    quit: false,
    forceQuit: false,
    cheatScrollPx: 0,
    keymap: null,
  };

  if (extraFields) Object.assign(state, extraFields);

  Object.defineProperty(state, 'mode', {
    get() { return this._modeStack[this._modeStack.length - 1].mode; },
    set(val) { this._modeStack[this._modeStack.length - 1].mode = val; },
    enumerable: true,
  });
  Object.defineProperty(state, 'commandBuf', {
    get() {
      const d = this._modeStack[this._modeStack.length - 1].data;
      if (this.mode === 'prompt' && d && d.prefix === ':') return d.buf;
      return this._commandBuf;
    },
    set(val) {
      const d = this._modeStack[this._modeStack.length - 1].data;
      if (this.mode === 'prompt' && d && d.prefix === ':') { d.buf = val; return; }
      this._commandBuf = val;
    },
    enumerable: true,
  });
  Object.defineProperty(state, 'searchBuf', {
    get() {
      const d = this._modeStack[this._modeStack.length - 1].data;
      if (this.mode === 'prompt' && d && d.prefix === '/') return d.buf;
      return this._searchBuf;
    },
    set(val) {
      const d = this._modeStack[this._modeStack.length - 1].data;
      if (this.mode === 'prompt' && d && d.prefix === '/') { d.buf = val; return; }
      this._searchBuf = val;
    },
    enumerable: true,
  });
  Object.defineProperty(state, 'promptCol', {
    get() {
      const d = this._modeStack[this._modeStack.length - 1].data;
      return d && d.col !== undefined ? d.col : this._promptCol;
    },
    set(val) {
      const d = this._modeStack[this._modeStack.length - 1].data;
      if (d && d.col !== undefined) { d.col = val; }
      else { this._promptCol = val; }
    },
    enumerable: true,
  });

  return state;
}

// --- createEditor: shared editor setup ---

function createEditor(opts) {
  const getLang = opts.getLang;
  const state = createState(opts.extraState);

  const km = createKeymap(state, {
    execCommand(cmd, buffer) {
      cmd = cmd.trim();
      if (cmd === 'w') {
        if (buffer.save()) {
          state.message = `Saved ${buffer.filename}`;
        } else {
          state.message = 'No filename';
        }
      } else if (cmd === 'q') {
        if (buffer.dirty) {
          state.message = 'Unsaved changes (use :q! to force)';
        } else {
          state.quit = true;
        }
      } else if (cmd === 'wq') {
        if (buffer.save()) {
          state.quit = true;
        } else {
          state.message = 'No filename';
        }
      } else if (cmd === 'q!') {
        state.quit = true;
        state.forceQuit = true;
      } else if (cmd === 'help') {
        if (buffer.dirty) {
          state.message = 'Unsaved changes (use :w first)';
        } else {
          state.loadFile = require('path').join(__dirname, '..', 'help', 'README');
        }
      } else if (/^\d+$/.test(cmd)) {
        const targetLine = parseInt(cmd, 10) - 1;
        const vi = km.findVisibleIndex(buffer, targetLine);
        state.cursor.line = vi;
        state.cursor.col = 0;
      } else {
        state.message = `Unknown command: ${cmd}`;
      }
    },
    getLang,
  });

  state.keymap = {
    normal: km.normalKeymap,
    select: km.selectKeymap,
    insert: km.insertKeymap,
    prompt: km.promptKeymap,
  };

  return { state, handleKey: km.handleKey, clampCursor: km.clampCursor, km };
}

// --- computeViewport: vertical + horizontal scroll ---

function computeViewport(state, editorRows, displayCols) {
  const half = Math.floor(editorRows / 2);
  if (state.selection) {
    const rStart = Math.min(state.selection.anchor, state.selection.head);
    const rEnd = Math.max(state.selection.anchor, state.selection.head);
    const regionHeight = rEnd - rStart + 1;
    if (regionHeight <= editorRows) {
      const regionMid = (rStart + rEnd) / 2;
      state.scroll = Math.round(regionMid) - half;
    } else {
      state.scroll = state.cursor.line - half;
    }
  } else {
    state.scroll = state.cursor.line - half;
  }

  if (state.cursor.col >= state.scrollX + displayCols - H_SCROLL_PAD)
    state.scrollX = state.cursor.col - displayCols + H_SCROLL_PAD + 1;
  if (state.cursor.col < state.scrollX + H_SCROLL_PAD)
    state.scrollX = Math.max(0, state.cursor.col - H_SCROLL_PAD);
  if (state.scrollX < 0) state.scrollX = 0;
}

// --- deriveCharRange: char-selection geometry ---

function deriveCharRange(state, visible) {
  if (state.selectionUnit !== 'char' || !state.selection) return null;
  const clampedAnchor = Math.max(0, Math.min(state.selection.anchor, visible.length - 1));
  const clampedHead = Math.max(0, Math.min(state.selection.head, visible.length - 1));
  const anchorLn = visible[clampedAnchor] ? visible[clampedAnchor].lineNum : 0;
  const headLn = visible[clampedHead] ? visible[clampedHead].lineNum : 0;
  const anchorCol = state.selection.anchorCol;
  const headCol = state.cursor.col;
  if (anchorLn < headLn || (anchorLn === headLn && anchorCol <= headCol)) {
    return { startLn: anchorLn, startCol: anchorCol, endLn: headLn, endCol: headCol };
  }
  return { startLn: headLn, startCol: headCol, endLn: anchorLn, endCol: anchorCol };
}

// --- deriveModeInfo: mode label + effective mode + cheat keymap ---

function deriveModeInfo(state) {
  let effectiveMode = state.mode === 'command' || state.mode === 'search' || state.mode === 'prompt' ? 'prompt' : state.mode;

  let keymap;
  if (effectiveMode === 'menu') {
    const d = state._modeStack[state._modeStack.length - 1].data;
    keymap = d.keymap || [];
  } else {
    keymap = (state.keymap && state.keymap[effectiveMode]) || [];
  }

  let label = ` ${effectiveMode.toUpperCase()} `;
  if (effectiveMode === 'prompt') {
    if (state.mode === 'prompt') {
      const d = state._modeStack[state._modeStack.length - 1].data;
      label = d && d.label ? ` ${d.label} ` : ' PROMPT ';
    } else {
      label = state.mode === 'command' ? ' COMMAND ' : ' SEARCH ';
    }
  } else if (effectiveMode === 'menu') {
    const d = state._modeStack[state._modeStack.length - 1].data;
    label = d && d.label ? ` ${d.label.toUpperCase()} ` : ' MENU ';
  } else if (effectiveMode === 'select' && state.selectionUnit) {
    label = ` SELECT:${state.selectionUnit.toUpperCase()} `;
  }

  return { effectiveMode, label, keymap };
}




// --- Web UI (from web/hu-web-src.js) ---

// --- mapKeyEvent (replaces lib/input.js for browser) ---

function mapKeyEvent(e) {
  const map = {
    ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right',
    Enter: 'enter', Backspace: 'backspace', Tab: 'tab', Escape: 'escape',
    Delete: 'delete', Home: 'home', End: 'end',
    PageUp: 'pageup', PageDown: 'pagedown',
  };

  let key = map[e.key] || e.key;
  const ctrl = e.ctrlKey || e.metaKey;
  const shift = e.shiftKey;

  // Normalize: Ctrl+Shift+letter comes through uppercase; we want lowercase for ctrl combos
  if (ctrl && key.length === 1 && key >= 'A' && key <= 'Z') {
    key = key.toLowerCase();
  }

  // Prevent browser defaults for keys we handle
  if (key === 'tab' || key === 'escape' || ctrl) {
    e.preventDefault();
  }
  // Also prevent Space in normal/select mode (will be checked by caller)
  // Prevent slash (search trigger)
  if (key === '/' || key === ':') {
    e.preventDefault();
  }

  return { key, ctrl, shift };
}


// --- Canvas renderer (replaces lib/render.js) ---

const COLORS = {
  bg:       '#1e1e1e',
  fg:       '#c8c8c8',
  dim:      '#666666',
  bold:     '#ffffff',
  cyan:     '#4ec9b0',
  yellow:   '#dcdcaa',
  gray:     '#666666',
  gutter:   '#858585',
  cheatBg:  '#c8c8c8',
  cheatFg:  '#1e1e1e',
  cheatDim: '#555555',
  statusBg: '#c8c8c8',
  statusFg: '#1e1e1e',

  // Selection backgrounds
  selLine:    '#264f78',
  selSection: '#5c2d5c',
  selIndent:  '#2d5c5c',
  selParent:  '#5c2d2d',

  // Mode label colors (dark bg)
  modeNormal: '#569cd6',
  modeSelect: '#dcdcaa',
  modeInsert: '#6a9955',
  modePrompt: '#c586c0',

  // Mode label colors (light cheat bar)
  modeNormalLight: '#1a5a9e',
  modeSelectLight: '#8a7a20',
  modeInsertLight: '#3a6a2a',
  modePromptLight: '#8a2a8a',

  // Cursor
  cursorNormal: '#ffffff',
  cursorInsert: '#00cc00',
};

const SEL_COLORS = {
  line: COLORS.selLine,
  section: COLORS.selSection,
  indent: COLORS.selIndent,
  parent: COLORS.selParent,
  char: COLORS.selLine,
};

const MODE_LABEL_COLORS = {
  normal: COLORS.modeNormal,
  select: COLORS.modeSelect,
  insert: COLORS.modeInsert,
  prompt: COLORS.modePrompt,
};

const MODE_LABEL_COLORS_LIGHT = {
  normal: COLORS.modeNormalLight,
  select: COLORS.modeSelectLight,
  insert: COLORS.modeInsertLight,
  prompt: COLORS.modePromptLight,
};

function renderCanvas(ctx, state, buffer, cols, rows, charW, lineH, pixelRatio) {
  const w = cols * charW;
  const h = rows * lineH;

  ctx.save();
  ctx.scale(pixelRatio, pixelRatio);

  // Clear
  ctx.fillStyle = COLORS.bg;
  ctx.fillRect(0, 0, w, h);

  const visible = buffer.visibleLines();
  const contentRows = rows - 4; // status + message + 2-row cheat bar
  const lang = getLang(buffer.filename);
  const lineComment = lang.lineComment;

  // --- Content area dimensions ---
  const gutterChars = 4;  // line number width
  const foldChars = 1;    // fold indicator
  const gutterTotal = gutterChars + foldChars + 1; // +1 space
  const displayCols = cols - gutterTotal;

  // Compute scroll and char-range via shared engine
  computeViewport(state, contentRows, displayCols);
  const charRange = deriveCharRange(state, visible);

  // Selection range
  const selStart = state.selection ? Math.min(state.selection.anchor, state.selection.head) : -1;
  const selEnd = state.selection ? Math.max(state.selection.anchor, state.selection.head) : -1;
  const selBg = SEL_COLORS[state.selectionUnit] || COLORS.selLine;

  // --- Row 0: Status bar ---
  const statusY = 0;
  ctx.fillStyle = COLORS.statusBg;
  ctx.fillRect(0, statusY, w, lineH);

  const modFlag = buffer.dirty ? ' [modified]' : '';
  const fname = buffer.filename || '[no file]';
  const actualLine = visible[state.cursor.line] ? visible[state.cursor.line].lineNum + 1 : 0;
  const colNum = state.cursor.col + 1;
  const statusLeft = ` ${fname}${modFlag} | ${actualLine}:${colNum}`;
  const statusRight = `${visible.length} lines `;

  ctx.fillStyle = COLORS.statusFg;
  ctx.fillText(statusLeft, 0, statusY + lineH * 0.78);
  ctx.fillText(statusRight, (cols - statusRight.length) * charW, statusY + lineH * 0.78);

  // --- Content rows ---

  for (let r = 0; r < contentRows; r++) {
    const y = (r + 1) * lineH;
    const visIdx = state.scroll + r;
    if (visIdx < 0 || visIdx >= visible.length) continue;

    const { lineNum, text } = visible[visIdx];
    const inSelection = state.selection && visIdx >= selStart && visIdx <= selEnd;

    // Selection background
    if (charRange && lineNum >= charRange.startLn && lineNum <= charRange.endLn) {
      // Char-level: partial row highlight
      const textX = gutterTotal * charW;
      let hlStart = 0;
      let hlEnd = text.length;
      if (lineNum === charRange.startLn) hlStart = charRange.startCol;
      if (lineNum === charRange.endLn) hlEnd = charRange.endCol + 1;
      const hlStartPx = textX + Math.max(0, hlStart - state.scrollX) * charW;
      const hlEndPx = textX + Math.max(0, hlEnd - state.scrollX) * charW;
      ctx.fillStyle = selBg;
      ctx.fillRect(hlStartPx, y, hlEndPx - hlStartPx, lineH);
    } else if (inSelection) {
      ctx.fillStyle = selBg;
      ctx.fillRect(0, y, w, lineH);
    }

    // Gutter: line number
    const gutterStr = String(lineNum + 1).padStart(gutterChars, ' ');
    ctx.fillStyle = COLORS.dim;
    ctx.fillText(gutterStr, 0, y + lineH * 0.78);

    // Fold indicator
    const foldX = gutterChars * charW;
    if (buffer.folds.has(lineNum)) {
      ctx.fillStyle = COLORS.cyan;
      ctx.fillText('\u25b8', foldX, y + lineH * 0.78); // ▸
    } else if (buffer.foldable(lineNum)) {
      ctx.fillStyle = COLORS.dim;
      ctx.fillText('\u25be', foldX, y + lineH * 0.78); // ▾
    }

    // Text content
    const textX = gutterTotal * charW;
    let lineText = text.slice(state.scrollX, state.scrollX + displayCols);

    // Fold suffix
    let foldSuffix = '';
    if (buffer.folds.has(lineNum)) {
      const count = buffer.foldedLineCount(lineNum);
      if (count > 0) foldSuffix = `  [${count} lines]`;
    }

    // Determine if this line is in char-level selection
    const isCharSelected = charRange && lineNum >= charRange.startLn && lineNum <= charRange.endLn;

    // Comment highlighting
    if (lineComment) {
      const commentIdx = lineText.indexOf(lineComment);
      if (commentIdx >= 0) {
        const before = lineText.slice(0, commentIdx);
        const comment = lineText.slice(commentIdx);
        ctx.fillStyle = (inSelection || isCharSelected) ? COLORS.bold : COLORS.fg;
        ctx.fillText(before, textX, y + lineH * 0.78);
        ctx.fillStyle = (inSelection || isCharSelected) ? COLORS.dim : COLORS.gray;
        ctx.fillText(comment, textX + commentIdx * charW, y + lineH * 0.78);
      } else {
        ctx.fillStyle = (inSelection || isCharSelected) ? COLORS.bold : COLORS.fg;
        ctx.fillText(lineText, textX, y + lineH * 0.78);
      }
    } else {
      ctx.fillStyle = (inSelection || isCharSelected) ? COLORS.bold : COLORS.fg;
      ctx.fillText(lineText, textX, y + lineH * 0.78);
    }

    // Fold suffix (always dim)
    if (foldSuffix) {
      ctx.fillStyle = COLORS.dim;
      ctx.fillText(foldSuffix, textX + lineText.length * charW, y + lineH * 0.78);
    }
  }

  // --- Yank panel overlay ---
  const yankFrame = state._modeStack.find(f => f.data && f.data.panel === 'yank');
  if (yankFrame) {
    renderYankPanelCanvas(ctx, state, cols, rows, charW, lineH);
  }

  // --- Message line (row rows-3) ---
  const msgY = (rows - 3) * lineH;
  ctx.fillStyle = COLORS.bg;
  ctx.fillRect(0, msgY, w, lineH);

  if (state.mode === 'prompt') {
    const d = state._modeStack[state._modeStack.length - 1].data;
    ctx.fillStyle = COLORS.fg;
    ctx.fillText(d.prefix + d.buf, 0, msgY + lineH * 0.78);
  } else if (state.mode === 'command') {
    ctx.fillStyle = COLORS.fg;
    ctx.fillText(':' + state.commandBuf, 0, msgY + lineH * 0.78);
  } else if (state.mode === 'search') {
    ctx.fillStyle = COLORS.fg;
    ctx.fillText('/' + (state.searchBuf || ''), 0, msgY + lineH * 0.78);
  } else if (state.message) {
    ctx.fillStyle = COLORS.dim;
    ctx.fillText(state.message, 0, msgY + lineH * 0.78);
  }

  // --- Cheat bar (row rows-1) ---
  const cheatButtons = renderCheatBarCanvas(ctx, state, cols, charW, lineH, (rows - 1) * lineH);

  // --- Cursor ---
  let cursorScreenRow, cursorScreenCol;
  if (state.mode === 'prompt') {
    const d = state._modeStack[state._modeStack.length - 1].data;
    cursorScreenRow = rows - 2;
    cursorScreenCol = d.col + d.prefix.length;
  } else if (state.mode === 'command' || state.mode === 'search') {
    cursorScreenRow = rows - 2;
    cursorScreenCol = state.promptCol + 1;
  } else {
    cursorScreenRow = state.cursor.line - state.scroll + 1;
    cursorScreenCol = state.cursor.col - state.scrollX + gutterTotal;
  }

  const cursorX = cursorScreenCol * charW;
  const cursorY = cursorScreenRow * lineH;

  if (state.mode === 'insert') {
    // Line cursor for insert mode
    ctx.fillStyle = COLORS.cursorInsert;
    ctx.fillRect(cursorX, cursorY + 1, 2, lineH - 2);
  } else {
    // Block cursor
    ctx.fillStyle = COLORS.cursorNormal;
    ctx.globalAlpha = 0.5;
    ctx.fillRect(cursorX, cursorY, charW, lineH);
    ctx.globalAlpha = 1.0;
  }

  ctx.restore();
  return cheatButtons;
}

function renderCheatBarCanvas(ctx, state, cols, charW, lineH, y) {
  const info = deriveModeInfo(state);
  const mode = info.effectiveMode;
  const keymap = info.keymap;
  const modeColor = MODE_LABEL_COLORS_LIGHT[mode] || COLORS.modeNormalLight;
  const modeLabel = info.label;

  // Build button list: split compound cheat keys into individual buttons
  const buttons = [];
  for (const entry of keymap) {
    if (!entry.cheat) continue;
    if (!entry.keys) continue; // skip display-only entries (like 'type insert')
    const [keyStr, descStr] = entry.cheat;
    const cheatKeys = keyStr.split('/');
    for (let ki = 0; ki < cheatKeys.length; ki++) {
      const displayKey = cheatKeys[ki];
      // Map display key to the actual key to fire
      let fireKey = displayKey;
      let ctrl = entry.ctrl || false;
      if (displayKey === 'Tab') fireKey = 'tab';
      else if (displayKey === 'Space') fireKey = ' ';
      else if (displayKey === 'Esc') fireKey = 'escape';
      else if (displayKey === 'Enter') fireKey = 'enter';
      else if (displayKey === 'Bksp') fireKey = 'backspace';
      else if (displayKey === 'Del') fireKey = 'delete';
      else if (displayKey.startsWith('C-')) { fireKey = displayKey.slice(2); ctrl = true; }
      else if (displayKey === '\u2191\u2193\u2190\u2192') fireKey = null; // arrow symbols, not tappable
      buttons.push({ displayKey, desc: descStr, fireKey, ctrl });
    }
  }

  // Background
  ctx.fillStyle = COLORS.cheatBg;
  ctx.fillRect(0, y, cols * charW, lineH);

  // Mode label
  ctx.fillStyle = modeColor;
  ctx.fillText(modeLabel, 0, y + lineH * 0.78);

  // Button area starts after mode label
  const btnPadX = charW * 0.5;   // horizontal padding inside button
  const btnGap = charW * 0.5;    // gap between buttons
  const btnRadius = 3;
  const modeLabelPx = modeLabel.length * charW;
  const areaStartX = modeLabelPx + charW;
  const areaEndX = cols * charW - charW;

  // Render buttons and build hit-test array
  const cheatButtons = [];
  let xPos = areaStartX - (state.cheatScrollPx || 0);

  for (let i = 0; i < buttons.length; i++) {
    const btn = buttons[i];
    const keyText = btn.displayKey;
    const descText = ' ' + btn.desc;
    const textW = (keyText.length + descText.length) * charW;
    const btnW = textW + btnPadX * 2;
    const btnX = xPos;
    const btnY = y + 2;
    const btnH = lineH - 4;

    // Skip buttons that are entirely off-screen left
    if (btnX + btnW < areaStartX) {
      xPos += btnW + btnGap;
      continue;
    }
    // Stop if button starts past right edge
    if (btnX > areaEndX) break;

    // Button background (rounded rect)
    ctx.fillStyle = '#aaaaaa';
    ctx.beginPath();
    ctx.roundRect(btnX, btnY, btnW, btnH, btnRadius);
    ctx.fill();

    // Key part (bold dark)
    ctx.fillStyle = COLORS.cheatFg;
    ctx.fillText(keyText, btnX + btnPadX, y + lineH * 0.78);

    // Desc part (dimmer)
    ctx.fillStyle = COLORS.cheatDim;
    ctx.fillText(descText, btnX + btnPadX + keyText.length * charW, y + lineH * 0.78);

    // Store hit rect in CSS pixels (pre-DPR) for tappable buttons
    if (btn.fireKey) {
      cheatButtons.push({
        x: btnX, y: y, w: btnW, h: lineH,
        key: btn.fireKey, ctrl: btn.ctrl || false,
      });
    }

    xPos += btnW + btnGap;
  }

  return cheatButtons;
}

function renderYankPanelCanvas(ctx, state, cols, rows, charW, lineH) {
  const panelWidthChars = Math.min(Math.floor(cols * 0.4), 50);
  const panelX = (cols - panelWidthChars) * charW;
  const panelRows = rows - 4;
  const startRow = 1;
  const panelW = panelWidthChars * charW;

  // Panel background
  ctx.fillStyle = '#252525';
  ctx.fillRect(panelX, startRow * lineH, panelW, panelRows * lineH);

  // Border
  ctx.strokeStyle = COLORS.dim;
  ctx.lineWidth = 1;
  ctx.strokeRect(panelX + 0.5, startRow * lineH + 0.5, panelW - 1, panelRows * lineH - 1);

  // Title
  ctx.fillStyle = COLORS.bold;
  ctx.fillText(' yanks ', panelX + charW, (startRow + 1) * lineH - lineH * 0.22);

  const registers = [{ key: '_', label: '(last yank)', lines: state.yankBuf }];
  for (const [k, v] of state.yankMap) {
    registers.push({ key: k, label: v.label || '', lines: v.lines });
  }

  let r = startRow + 1;
  for (let ri = 0; ri < registers.length && r < startRow + panelRows - 1; ri++) {
    const reg = registers[ri];
    const selected = ri === state.yankPanelIdx;
    const rowY = r * lineH;

    if (selected) {
      ctx.fillStyle = COLORS.selLine;
      ctx.fillRect(panelX, rowY, panelW, lineH);
    }

    // Key label
    ctx.fillStyle = selected ? COLORS.bold : COLORS.yellow;
    ctx.fillText(` ${selected ? '\u25b8' : ' '} ${reg.key}`, panelX, rowY + lineH * 0.78);
    ctx.fillStyle = COLORS.dim;
    ctx.fillText(`  ${reg.label}`, panelX + 5 * charW, rowY + lineH * 0.78);
    r++;

    // Preview lines
    const preview = reg.lines.slice(0, 3);
    for (const pline of preview) {
      if (r >= startRow + panelRows - 1) break;
      const truncated = pline.slice(0, panelWidthChars - 8);
      ctx.fillStyle = COLORS.dim;
      ctx.fillText(`     ${truncated}`, panelX, r * lineH + lineH * 0.78);
      r++;
    }
    if (reg.lines.length > 3 && r < startRow + panelRows - 1) {
      ctx.fillStyle = COLORS.dim;
      ctx.fillText(`     ... (${reg.lines.length} lines)`, panelX, r * lineH + lineH * 0.78);
      r++;
    }
    r++; // blank separator
  }

  // Hints at bottom
  const hintRow = startRow + panelRows;
  if (hintRow < rows) {
    ctx.fillStyle = COLORS.dim;
    ctx.fillText(' j/k:nav p:paste s:save d:del Esc:close', panelX, hintRow * lineH + lineH * 0.78);
  }
}


// ============================================================
// <h-edit> Web Component
// ============================================================

class HEdit extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this._buffer = null;
    this._editor = null;
    this._canvas = null;
    this._ctx = null;
    this._charW = 0;
    this._lineH = 0;
    this._rows = 0;
    this._cols = 0;
    this._fileMap = {};
    this._cheatButtons = [];
    this._resizeObserver = null;
    this._boundKeyDown = this._onKeyDown.bind(this);
  }

  connectedCallback() {
    // Shadow DOM structure
    this.shadowRoot.innerHTML = `
      <style>
        :host {
          display: block;
          position: relative;
          overflow: hidden;
          outline: none;
        }
        canvas {
          display: block;
          width: 100%;
          height: 100%;
        }
      </style>
      <canvas></canvas>
    `;

    this._canvas = this.shadowRoot.querySelector('canvas');
    this._ctx = this._canvas.getContext('2d');

    // Parse slotted files
    this._parseSlottedFiles();

    // Create buffer from first file
    const filenames = Object.keys(this._fileMap);
    const firstName = filenames[0] || 'untitled';
    const firstContent = this._fileMap[firstName] || '';

    this._buffer = createBuffer(firstName, {
      content: firstContent,
      onSave: (filename, content) => {
        // Update virtual file map on save
        this._fileMap[filename] = content;
        this.dispatchEvent(new CustomEvent('save', {
          detail: { filename, content },
          bubbles: true,
        }));
      },
    });

    // Run language-specific onOpen hook
    const initLang = getLang(firstName);
    if (initLang.lineComment) this._buffer.lineComment = initLang.lineComment;
    if (initLang.onOpen) {
      initLang.onOpen(this._buffer);
    }

    // Create editor
    this._editor = createEditor({ getLang });

    // Measure font and dimensions
    this._measureFont();
    this._updateDimensions();

    // Wire events
    this.setAttribute('tabindex', '0');
    this.addEventListener('keydown', this._boundKeyDown);

    // Focus on click
    this._canvas.addEventListener('mousedown', () => this.focus());

    // Touch events for mobile
    this._canvas.addEventListener('touchstart', this._onTouchStart.bind(this), { passive: false });
    this._canvas.addEventListener('touchmove', this._onTouchMove.bind(this), { passive: false });
    this._canvas.addEventListener('touchend', this._onTouchEnd.bind(this), { passive: false });

    // Resize observer
    this._resizeObserver = new ResizeObserver(() => {
      this._measureFont();
      this._updateDimensions();
      this._render();
    });
    this._resizeObserver.observe(this);

    // Initial render
    this._render();
    this.focus();
  }

  disconnectedCallback() {
    if (this._resizeObserver) {
      this._resizeObserver.disconnect();
      this._resizeObserver = null;
    }
    this.removeEventListener('keydown', this._boundKeyDown);
  }

  _parseSlottedFiles() {
    this._fileMap = {};
    const scripts = this.querySelectorAll('script[data-path]');
    for (const script of scripts) {
      const path = script.getAttribute('data-path');
      let content = script.textContent;
      // Trim leading newline (common in inline content)
      if (content.startsWith('\n')) content = content.slice(1);
      // Trim trailing whitespace/newline
      content = content.replace(/\s+$/, '');
      this._fileMap[path] = content;
    }
  }

  _measureFont() {
    // Get computed font from the host element
    const style = getComputedStyle(this);
    const font = style.font || `${style.fontSize || '14px'} ${style.fontFamily || 'monospace'}`;
    this._ctx.font = font;
    this._font = font;

    // Measure character width
    const metrics = this._ctx.measureText('M');
    this._charW = metrics.width;

    // Line height
    const fontSize = parseFloat(style.fontSize) || 14;
    this._lineH = Math.ceil(fontSize * 1.4);
  }

  _updateDimensions() {
    const rect = this.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;

    this._canvas.width = Math.floor(rect.width * dpr);
    this._canvas.height = Math.floor(rect.height * dpr);
    this._canvas.style.width = rect.width + 'px';
    this._canvas.style.height = rect.height + 'px';

    // Re-set font after canvas resize (clears context state)
    this._ctx.font = this._font;

    this._cols = Math.floor(rect.width / this._charW);
    this._rows = Math.floor(rect.height / this._lineH);
  }

  _onKeyDown(e) {
    // Don't capture if canvas doesn't have focus
    if (this.shadowRoot.activeElement && this.shadowRoot.activeElement !== this._canvas) return;

    const key = mapKeyEvent(e);

    // Prevent Space from scrolling in normal/select mode
    if (key.key === ' ' && (this._editor.state.mode === 'normal' || this._editor.state.mode === 'select')) {
      e.preventDefault();
    }

    // Prevent backspace from navigating back
    if (key.key === 'backspace') {
      e.preventDefault();
    }

    this._editor.handleKey(key, this._buffer);

    // Handle quit
    if (this._editor.state.quit) {
      this.dispatchEvent(new CustomEvent('quit', { bubbles: true }));
      this._editor.state.quit = false;
      this._editor.state.forceQuit = false;
    }

    this._render();
  }

  _onTouchStart(e) {
    e.preventDefault();
    this.focus();
    const touch = e.touches[0];
    const rect = this._canvas.getBoundingClientRect();
    this._touchStartX = touch.clientX - rect.left;
    this._touchStartY = touch.clientY - rect.top;
    this._touchStartTime = Date.now();
    this._touchMoved = false;
    this._touchStartCheatScrollPx = this._editor ? (this._editor.state.cheatScrollPx || 0) : 0;
  }

  _onTouchMove(e) {
    e.preventDefault();
    if (!this._editor) return;
    const touch = e.touches[0];
    const rect = this._canvas.getBoundingClientRect();
    const x = touch.clientX - rect.left;
    const y = touch.clientY - rect.top;
    const dx = x - this._touchStartX;
    const dy = y - this._touchStartY;

    if (Math.abs(dx) > 10 || Math.abs(dy) > 10) {
      this._touchMoved = true;
    }

    // Horizontal scroll on cheat bar row (bottom row)
    const cheatBarTop = (this._rows - 1) * this._lineH;
    if (this._touchStartY >= cheatBarTop) {
      this._editor.state.cheatScrollPx = Math.max(0, this._touchStartCheatScrollPx - dx);
      this._render();
    }
  }

  _onTouchEnd(e) {
    e.preventDefault();
    if (!this._editor || !this._buffer) return;

    // If it was a tap (not a swipe)
    if (!this._touchMoved) {
      const x = this._touchStartX;
      const y = this._touchStartY;

      // Hit-test against cheat buttons
      const buttons = this._cheatButtons || [];
      for (const btn of buttons) {
        if (x >= btn.x && x <= btn.x + btn.w && y >= btn.y && y <= btn.y + btn.h) {
          this._editor.handleKey({ key: btn.key, ctrl: btn.ctrl, shift: false }, this._buffer);
          if (this._editor.state.quit) {
            this.dispatchEvent(new CustomEvent('quit', { bubbles: true }));
            this._editor.state.quit = false;
            this._editor.state.forceQuit = false;
          }
          this._render();
          return;
        }
      }
    }

    this._touchStartX = null;
    this._touchStartY = null;
  }

  _render() {
    if (!this._ctx || !this._buffer || !this._editor) return;

    const dpr = window.devicePixelRatio || 1;
    this._ctx.font = this._font;

    this._cheatButtons = renderCanvas(
      this._ctx,
      this._editor.state,
      this._buffer,
      this._cols,
      this._rows,
      this._charW,
      this._lineH,
      dpr
    ) || [];
  }

  // --- Public API ---

  get filename() {
    return this._buffer ? this._buffer.filename : '';
  }

  get content() {
    return this._buffer ? this._buffer.lines.join('\n') + '\n' : '';
  }

  get mode() {
    return this._editor ? this._editor.state.mode : 'normal';
  }

  get files() {
    return { ...this._fileMap };
  }

  openFile(path) {
    if (this._fileMap[path] && this._editor && this._buffer) {
      this._editor.state.mode = 'normal';
      const content = this._fileMap[path];
      this._buffer.filename = path;
      this._buffer.lines = content.split('\n');
      if (this._buffer.lines.length > 1 && this._buffer.lines[this._buffer.lines.length - 1] === '') {
        this._buffer.lines.pop();
      }
      this._buffer.dirty = false;
      this._buffer.folds.clear();
      this._buffer._visibleCache = null;
      this._editor.state.cursor = { line: 0, col: 0 };
      this._editor.state.scroll = 0;
      this._editor.state.undoStack = [];
      this._editor.state.redoStack = [];
      const loadLang = getLang(path);
      this._buffer.lineComment = loadLang.lineComment || null;
      if (loadLang.onOpen) {
        loadLang.onOpen(this._buffer);
      }
      this._render();
    }
  }
}

customElements.define('h-edit', HEdit);
