#!/usr/bin/env node
// build.js — Generates web/hu-web.js by concatenating shared modules + web source
// Usage: node build.js

'use strict';

const fs = require('fs');
const path = require('path');

// --- 1. Read lang configs and generate LANG_CONFIGS + getLang ---

function buildLangConfigs() {
  const langDir = path.join(__dirname, 'lang');
  const skip = new Set(['index.js', 'media.js', 'hu.js']);
  const configs = [];

  for (const file of fs.readdirSync(langDir).sort()) {
    if (!file.endsWith('.js') || skip.has(file)) continue;
    const cfg = require(path.join(langDir, file));
    if (cfg.type !== 'editable') continue;
    configs.push(cfg);
  }

  const lines = ['const LANG_CONFIGS = ['];
  for (const cfg of configs) {
    lines.push('  {');
    lines.push(`    type: '${cfg.type}',`);
    lines.push(`    name: '${cfg.name}',`);
    lines.push(`    extensions: [${cfg.extensions.map(e => `'${e}'`).join(', ')}],`);
    lines.push(`    lineComment: ${cfg.lineComment === null ? 'null' : `'${cfg.lineComment}'`},`);
    lines.push(`    selectionUnits: [${cfg.selectionUnits.map(s => `'${s}'`).join(', ')}],`);
    if (cfg.onOpen) {
      // Serialize as method shorthand (toString() gives "onOpen(buffer) { ... }")
      lines.push(`    ${cfg.onOpen.toString()},`);
    }
    lines.push('  },');
  }
  lines.push('];');

  lines.push('');
  lines.push('const LANG_DEFAULT = {');
  lines.push("  type: 'editable',");
  lines.push("  name: 'default',");
  lines.push('  lineComment: null,');
  lines.push("  selectionUnits: ['line', 'section', 'indent', 'parent'],");
  lines.push('  onOpen: null,');
  lines.push('};');
  lines.push('');
  lines.push('function getLang(filename) {');
  lines.push('  if (!filename) return LANG_DEFAULT;');
  lines.push('  for (const cfg of LANG_CONFIGS) {');
  lines.push('    for (const ext of cfg.extensions) {');
  lines.push('      if (filename.endsWith(ext)) return cfg;');
  lines.push('    }');
  lines.push('  }');
  lines.push('  return LANG_DEFAULT;');
  lines.push('}');

  return lines.join('\n');
}

// --- 2. Strip require/module.exports/use-strict from a module source ---

function stripModule(src) {
  return src.split('\n').filter(line => {
    const t = line.trim();
    if (t === "'use strict';") return false;
    if (/^const\s+.*=\s*require\(/.test(t)) return false;
    if (/^const\s*\{[^}]*\}\s*=\s*require\(/.test(t)) return false;
    if (t.startsWith('module.exports')) return false;
    if (t.startsWith('if (typeof module')) return false;
    return true;
  }).join('\n');
}

// --- 3. Assemble and write ---

const header = `'use strict';

// ============================================================
// hu-web.js — Generated by build.js. Do not edit directly.
// A vim-style, indentation-aware <h-edit> web component.
// Source: lib/constants.js + lang/*.js + lib/buffer.js + lib/keymap.js + lib/engine.js + web/hu-web-src.js
// ============================================================
`;

const langBlock = buildLangConfigs();
const constantsSrc = fs.readFileSync(path.join(__dirname, 'lib/constants.js'), 'utf8');
const bufferSrc = fs.readFileSync(path.join(__dirname, 'lib/buffer.js'), 'utf8');
const keymapSrc = fs.readFileSync(path.join(__dirname, 'lib/keymap.js'), 'utf8');
const engineSrc = fs.readFileSync(path.join(__dirname, 'lib/engine.js'), 'utf8');
const webSrc = fs.readFileSync(path.join(__dirname, 'web/hu-web-src.js'), 'utf8');

const output = [
  header,
  '// --- Constants (from lib/constants.js) ---\n',
  stripModule(constantsSrc),
  '\n\n// --- Language configs (generated from lang/) ---\n',
  langBlock,
  '\n\n// --- createBuffer (from lib/buffer.js) ---\n',
  stripModule(bufferSrc),
  '\n\n// --- createKeymap (from lib/keymap.js) ---\n',
  stripModule(keymapSrc),
  '\n\n// --- Engine (from lib/engine.js) ---\n',
  stripModule(engineSrc),
  '\n\n// --- Web UI (from web/hu-web-src.js) ---\n',
  webSrc,
].join('\n');

const outPath = path.join(__dirname, '..', 'lib/web/feather-1/hu-web.js');
fs.writeFileSync(outPath, output);

const lineCount = output.split('\n').length;
console.log(`Built ${outPath} (${lineCount} lines)`);
